### PR TITLE
Adding Several Non-Spatial Segregation Functions with appropriate docstrings and notebooks that presents them

### PR DESCRIPTION
**Pull request by renanxcortes**
Serge, this pull requests presents currently several independent functions with appropriate docstring for the PySAL module of segregation (I worked only in the non-spatial, for now) as following:

- Dissimilarity (D)
- Gini (G)
- Entropy (H)
- Isolation (xPx)
- Exposure (xPy)
- Atkinson (A)
- Correlation Ratio (V)
- Concentration Profile (R)
- Modified Dissimilarity (Dct)
- Modified Gini (Gct)
- Bias-Corrected Dissimilarity (Dbc)
- Density-Corrected Dissimilarity (Ddc)

ps.: also I changed the random labelling approach to compare two groups (either two cities or same city between two points in time) the appropriate labelling for each permutation in a function called 'compare_segregation'. The results improved a lot. Also, more notebooks were added and old ones were improved to contemplate the new features.

### CODE REVIEW

**Comment by ljwolf** [comment]
Hey, thanks for putting this together, it looks really good. 

I know I'm not maintainer here, so feel free to reject this suggestion. But, as a like... "meta" programing idea, it's really nice to provide some consistency in how you identify the *outputs* of your computational classes. In `sklearn`, they do this by making sure that like, any classifier uses the `labels_` attribute. 

I mimicked this over in ESDA 3 years ago by adding `_statistic`  attribute to most classes. (e.g. [G stat](https://github.com/pysal/pysal/blob/master/pysal/esda/getisord.py#L164)). Keeping a consistent interface makes the library more accessible and easier for users to understand. Calling the various statistics by their greek (or roman) letter names helps keep close to the technical code, but can be v. confusing for folks who want to use the code from other domains. Plus, the inconsistency severely affects how easy it is to program *across* the measures. 

I'm not a maintainer here and not a contributor (yet) to this codebase, but this is just some perspective I gained from my own experience in `esda`.

**Comment by renanxcortes** [comment]
Hi, Levi, thanks for the suggestion!

Yeah, I think this is really good idea for consistency and, specially, for future use of these functions combined (for the inference framework, I believe it's going to be very likely that we would have code across measures, as you mentioned).

I'm gonna implement this, I just want to make sure what would be the most appropriate way. I think there are two possible scenarios:

The first one is creating a ClassName.statistic and removing all the greek/original letters attributes.

Another option is to keep all the greek/original letters as attributes (in order to be consistent with explained formulas in the formulas/notebooks), but adding a consistent 'statistic()' method for each Class and then explain this class somewhere in the docstring and changing the examples by using this method 'ClassName.statistic()'

What do you think? I have the impression that the second option would be more appropriate.

In either case, it's going to be great if you want to become a contributor for this branch! :)

**Comment by renanxcortes** [comment]
Hi, Levi, thanks for the suggestion!

Yeah, I think this is really good idea for consistency and, specially, for future use of these functions combined (for the inference framework, I believe it's going to be very likely that we would have code across measures, as you mentioned).

I'm gonna implement this, I just want to make sure what would be the most appropriate way. I think there are some possible scenarios:

The first one is creating a ClassName.statistic and removing all the greek/original letters attributes.

Another option is to keep all the greek/original letters as attributes (in order to be consistent with explained formulas in the formulas/notebooks), but adding a consistent 'statistic()' method for each Class and then explain this class somewhere in the docstring and changing the examples by using this method 'ClassName.statistic()'... it seems like the '_statistic' in esda is a method instead of an attribute, therefore I could also add this internal method (with the underscore) for each segregation measure.

What do you think? I have the impression that the second option (with '_statistic()' just as in esda) would be more appropriate.

In either case, it's going to be great if you want to become a contributor for this branch! :)

**Comment by renanxcortes** [comment]
@ljwolf now I double checked the ESDA code and tested myself I understood that this is, actually, a hidden attribute. Okay! This is a great idea! I'll do that. Thanks!

**Comment by ljwolf** [comment]
If I did it again, I'd actually make the attribute public! In hindsight, making it private like... hides it from users looking for a consistent way to access the statistic. 

At the time, I was nervous about adding something to the API. You get to start afresh, so make it look however you think will be easiest for you to maintain and for users to understand.

**Comment by renanxcortes** [comment]
Okay, this makes sense also! So, perhaps, I naming the public attribute name to 'value' instead of 'statistic' would be more appropriate, is this okay?

**Comment by ljwolf** [comment]
`value` is fine... what does `scipy.stats` call it in their `namedtuples`?

**Comment by renanxcortes** [comment]
They call it 'statistic'! Okay, in order to make this module more harmonized, I'll change to 'statistic', no problem! Thanks!

**Pull request merged**
